//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public Nullable<int> ID { get; set; }
        public string FIO { get; set; }
        public string Data { get; set; }
        public string Status { get; set; }
        public string Phone { get; set; }
        public string Zakaz1 { get; set; }
        public int ID_sotryd { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
